### ISSUE TITLE
Restructured (cleaned-up) version of ciefunction (July 2017) uploaded in new branch 'aangstroms_escapade'.

### ISSUE THREAD

**Issue by janhenrikwold** [ifarup/ciefunctions#181]
**Revision 10 July 2017.**  
Heavily revised version of 'CIE Functions' 
(Uploaded in new branch 'aangstroms_escapade'):
- General restructuring/clean-up to make the program code easier to
  read.
- The calculations are in principle the same as in previous versions,
  but the code is made more modular, among others by introducing
  a number of new functions corresponding to the different colorimetric
  representations provided (listed in the drop-down menu).
- Many variable names are replaced by names/symbols that resemble
  standard colorimetric nomenclature (in particular, some greek letters
 (Unicode) occur).
- To some extent, explanatory comments are added.
- New feature providing plots and tables of the CIE 2006 cone
  fundamentals as given in logarithmic units are included.
- A bug relating to the reading of numbers from the 'field_size'
  spinbox is fixed.
- Some minor other fixes are made.

**Comment by ifarup** [comment]
Merged into master branch and included from v1.0.0b3
