### ISSUE TITLE
Table windows goes black on Windows 7

### ISSUE THREAD

**Issue by ifarup** [ifarup/ciefunctions#183]
Copied from issue #182 comment by dlpalpha:

"""
See if this reproduces for you: (1) Launch CIE Functions; (2) Select "CIE XYZ cone-fundamental-based" etc. from the dropdown menu; (3) Click the Table tab and notice the window is black; (4) Click any other option from the dropdown and click its Table tab -- notice those windows are black, too.

Now try this: (1) Launch; (2) Click the Table tab for the plot that is displayed by default (CIE LMS cone fundamentals); (3) Notice that the table is populated; (4) Select any other dropdown item and click its Table tab -- notice that those tables populate, too.

So -- for me, anyway -- the bug has something to do with which table is viewed first: If the LMS fundamentals table is viewed first, all is well afterward. If I try to view a different table first, the table-populating code stops executing.

My system info: Windows 7 Pro SP1 (fully updated) running under Parallels Desktop 13.2.0 on OSX 10.12.6.
"""

I have tested v1.0.0b3 on updated Windows 10 and Ubuntu 16.04 and not been able to reproduce the bug.

**Comment by dlpalpha** [comment]
To make certain, I uninstalled CIE Functions, downloaded another copy, and re-installed. Everything I described before replicates on my Win7 system.

**Comment by dlpalpha** [comment]
bump.

BTW, I suspect I was wrong when I guessed that the table-populating code stops executing. That's unlikely because the graphs update. Seems more apt to be a GUI problem.

**Comment by ifarup** [comment]
I still haven't got access to a Windows 7 system. Would it be possible for you to try to install python3 on windows 7 and then install ciefunctions with pip (from pypi, i.e., "pip install ciefunctions" on the command line)?

**Comment by dlpalpha** [comment]
Perhaps with more detailed directions I can do what you ask. For example, where do I find a Win7-compatible Python 3 installer, and exactly how do I get the command prompt for the "pip install" etc. command?

**Comment by dlpalpha** [comment]
I installed the 64-bit Python 3.6.4 for Windows release I found at https://www.python.org/downloads/release/python-364/ and rebooted. I then found my way to the command line, where the pip command errored:

C:\Users\dp>pip install ciefunctions
'pip' is not recognized as an internal or external command, operable program or batch file.

I presume I've made a newbie mistake(?)

**Comment by dlpalpha** [comment]
I installed the 64-bit Anaconda3 5.1.0/Python 3.6 for Windows version I found at the link you gave, using the default options. That is, I skipped the options to (1) add Anaconda to the PATH environmental variable, and (2) register Anaconda as my default Python 3.6 (I couldn't find clear directions for unregistering the Python 3.6 I'd installed already). I still get:

C:\Users\dp>pip install ciefunctions
'pip' is not recognized as an internal or external command, operable program or batch file.

which I'm guessing is because I need to register the new Python (but don't know how).

**Comment by dlpalpha** [comment]
I tried un-installing both Python installations, then re-installing Anaconda, and rebooting. This time, the default install made Anaconda my default Python. The pip command yields the same result, though.

**Comment by dlpalpha** [comment]
Is there anything more I might do to assist fixing this apparent bug?

**Comment by ifarup** [comment]
Thanks. At the present stage I think not. I guess we will have to set up a testing system with all relevant platforms here for continuous testing.

**Comment by dlpalpha** [comment]
Ok. If the time comes, I'm willing to assist with beta testing under Win 7 and OSX.

**Comment by ifarup** [comment]
The final approval from CIE will still take some time. Microsoft has announced that Windows 7 will only be supported one more year from now (until 14th January 2020). Thus, we will not put any effort into supporting it.
